module.exports = {

    tmp_dir: 'tmp', // collecting locale src files

    /******************************************************************************
     * BUILD
     * Environment settings
     *****************************************************************************/
    build: {
        root: 'build',
        css: 'build/assets/css/invius.css',
        assets: 'build/assets/'
    },

    /******************************************************************************
     * PRODUCTION
     * Environment settings
     *****************************************************************************/
    production: {
        root: 'production',
        css: 'production/invius.css',
        js: 'production/invius.js',
        assets: 'production/assets/'
    },

    /******************************************************************************
     * TEST COVERAGE
     * output settings
     *****************************************************************************/
    coverage: {
        root: 'coverage'
    },

    mock_files: ['mocks/**/*'],

    /******************************************************************************
     * SOURCES
     *****************************************************************************/
    app_files: {
        index: ['src/js/index.html'],
        main: ['src/js/app.js'],
        js: ['src/js/**/*.js', '!src/js/**/*.spec.js'],
        jsunit: ['src/js/**/*.spec.js'],

        locale: {
            vendor: [''], // ALL languages from lib dist
            src: ['src/js/**/*.locale.json'], // us_US (default language)
            translations: ['locale/**.*.locale.json'] // all other languages (generated by translation)
        },

        tpl: ['src/js/**/*.tpl.html'],

        html: ['src/index.html'],

        sass: 'src/sass/main.scss',

        assets: 'src/assets',

        config: [
            'src/config.json',
        ]
    },

    grunt_files: ['Gruntfile.js', 'grunt/**/*.js'],

    test_files: {
        js: ['vendor/angular-mocks/angular-mocks.js'],
        unit: ['src/js/**/*.spec.js']
    },
    vendor_files: {
        js: [
            'vendor/angular/angular.js',
            'vendor/angular-animate/angular-animate.js',
            'vendor/angular-bootstrap/ui-bootstrap.js',
            'vendor/angular-bootstrap/ui-bootstrap-tpls.js',
            'vendor/angular-deferred-bootstrap/angular-deferred-bootstrap.js',
            'vendor/angular-sanitize/angular-sanitize.js',
            'vendor/angular-route/angular-route.js',
            'vendor/angular-cookies/angular-cookies.js'
        ],
        css: [],
        fonts: [],
        maps: [],
        assets: [],
        publish: []
    }
};
